<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

/**
 * Seeder to generate test users with known credentials for manual testing.
 * Creates 17 users: 5 teachers, 2 representatives, 10 students.
 * Combined with UserSeeder (1 admin), total = 18 test users.
 * Bulk demo data (500 students, 25 teachers) is generated by DemoDataSeeder.
 */
class TestUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $total = 5 + 2 + 10; // 17

        $bar = $this->command->getOutput()->createProgressBar($total);
        $bar->setFormat(' %current%/%max% [%bar%] %percent:3s%% — %message%');
        $bar->setMessage('Iniciando...');
        $bar->start();

        $bar->setMessage('Creando profesores de prueba...');
        $this->createUsersByRole('profesor', 5, 90000001, $bar);

        $bar->setMessage('Creando representantes de prueba...');
        $this->createUsersByRole('representante', 2, 90000010, $bar);

        $bar->setMessage('Creando alumnos de prueba...');
        $this->createUsersByRole('alumno', 10, 90000020, $bar);

        $bar->finish();
        $this->command->newLine(2);
    }

    /**
     * Create multiple users with a specific role.
     */
    private function createUsersByRole(string $role, int $count, int $startCedula, mixed $bar): void
    {
        for ($i = 0; $i < $count; $i++) {
            $cedula = (string) ($startCedula + $i);
            $email = "user{$cedula}@amantina.test";

            /** @var User $user */
            $user = User::updateOrCreate(
                ['cedula' => $cedula],
                [
                    'name' => "Usuario {$cedula}",
                    'email' => $email,
                    'password' => Hash::make('password'),
                    'phone' => '04120000000',
                    'address' => 'Dirección de prueba',
                    'is_active' => true,
                    'is_transfer' => false,
                    'institution_origin' => null,
                ]
            );

            $user->assignRole($role);
            $bar->advance();
        }
    }
}
